org: ${env:ORG}
service: proyecto-api-resenia

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: ${env:IAM_ROLE_ARN}
  environment:
    TIENDA_TABLE: ${self:service}-${sls:stage}-tienda  # Usamos la variable `${self:service}` para obtener el nombre del servicio y `${sls:stage}` para el entorno
    RESENA_TABLE: ${self:service}-${sls:stage}-resena  # Tabla para las reseñas

  httpApi:
    cors:
      allowedOrigins:
        - '*'  # Permite cualquier origen
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
      allowedMethods:
        - OPTIONS
        - GET
        - POST
      allowCredentials: false

functions:
  CrearResenia:
    handler: resenia.crearResenia
    events:
      - http:
          path: /resenia/crear
          method: post
          cors: true
          integration: lambda
    name: ${self:service}-${opt:stage, 'dev'}-crear-proyecto

resources:
  Resources:
    TablaResenias:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.RESENA_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: resenia_id
            AttributeType: S
          - AttributeName: producto_id
            AttributeType: S
          - AttributeName: usuario_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: resenia_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        LocalSecondaryIndexes:
          - IndexName: ProductoIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: producto_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: UsuarioIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: usuario_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

