org: dannamendez
service: api-resenia

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::385301667309:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_resenias
  apiGateway:
    cors: # Configuración global de CORS
      origins:
        - '*'  # Permite solicitudes de cualquier origen
      allowCredentials: false  # Cambiar según lo necesario (true si deseas habilitar cookies o autenticación)
      allowHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE

functions:
  crear:
    handler: resenia.crearResenia
    events:
      - http:
          path: /resenia/crear
          method: post
          cors: true  # Habilitado por cada evento
          integration: lambda

resources:
  Resources:
    TablaResenias:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id#producto_id
            AttributeType: S
          - AttributeName: resenia_id
            AttributeType: S
          - AttributeName: fecha
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id#producto_id
            KeyType: HASH
          - AttributeName: resenia_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        LocalSecondaryIndexes:
          - IndexName: FechaIndex
            KeySchema:
              - AttributeName: tenant_id#producto_id
                KeyType: HASH
              - AttributeName: fecha
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
