org: dannamendez
service: api-tienda

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::385301667309:role/LabRole  # ARN del rol LabRole
  environment:
    TIENDA_TABLE: ${self:service}-${sls:stage}-tienda  # Usamos la variable `${self:service}` para obtener el nombre del servicio y `${sls:stage}` para el entorno
  apiGateway:
    cors: # Configuración global de CORS
      origins:
        - '*'  # Permite solicitudes de cualquier origen
      allowCredentials: false  # Cambiar según lo necesario (true si deseas habilitar cookies o autenticación)
      allowHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE

functions:
  createOrder:
    handler: create_order.handler
    events:
      - http:
          path: /pedidos/create
          method: post
          cors: true  # CORS habilitado para este endpoint

  getOrder:
    handler: get_order.handler
    events:
      - http:
          path: /pedidos/get
          method: get
          cors: true  # CORS habilitado para este endpoint

  deleteOrder:
    handler: delete_order.handler
    events:
      - http:
          path: /usuarios/delete
          method: delete
          cors: true  # CORS habilitado para este endpoint

  fetchOrder:
    handler: fetch_user.handler
    events:
      - http:
          path: /usuarios/fetch
          method: get
          cors: true  # CORS habilitado para este endpoint

resources:
  Resources:
    PedidosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PEDIDOS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: pedido_id
            AttributeType: S
          - AttributeName: estado
            AttributeType: S
          - AttributeName: tenant_id#usuario_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: pedido_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        LocalSecondaryIndexes:
          - IndexName: EstadoIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: estado
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: UsuarioEstadoIndex
            KeySchema:
              - AttributeName: tenant_id#usuario_id
                KeyType: HASH
              - AttributeName: estado
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
