org: dannamendez
service: api-tienda

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::385301667309:role/LabRole  # ARN del rol LabRole
  environment:
    TIENDA_TABLE: ${self:service}-${sls:stage}-tienda  # Usamos la variable `${self:service}` para obtener el nombre del servicio y `${sls:stage}` para el entorno
  apiGateway:
    cors: # Configuración global de CORS
      origins:
        - '*'  # Permite solicitudes de cualquier origen
      allowCredentials: false  # Cambiar según lo necesario (true si deseas habilitar cookies o autenticación)
      allowHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE

functions:
  createTienda:
    handler: create_tienda.handler
    events:
      - http:
          path: /tienda/create
          method: post
          cors: true  # Habilitado por cada evento
          integration: lambda

  fetchTienda:
    handler: fetch_tienda.handler
    events:
      - http:
          path: /tienda/fetch
          method: get
          cors: true  # Habilitado por cada evento
          integration: lambda
    
  getTienda:
    handler: get_tienda.handler
    events:
      - http:
          path: /tienda/{tenant_id}
          method: get
          cors: true  # Habilitado por cada evento
          integration: lambda

resources:
  Resources:
    TiendaTable:  # Nombre del recurso de la tabla DynamoDB
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-tienda  # El nombre de la tabla se genera de manera similar
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
