org: ${env:ORG}
service: proyecto-api-producto

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 29  # Timeout de las funciones Lambda y API Gateway ajustado a 29 segundos
  iam:
    role: ${env:IAM_ROLE_ARN}
  environment:
    PRODUCTO_TABLE: ${sls:stage}-proyecto_productos
    VALIDAR_TOKEN_LAMBDA_NAME: proyecto-api-usuarios-${sls:stage}-ValidarTokenAcceso
    BUCKET_NAME: ${sls:stage}-tienda-grupo-nahia-y-compania-proyecto
    SUBIR_IMAGENES_LAMBDA_NAME: ${self:service}-${sls:stage}-subirImagen
    OBTENER_URL_LAMBDA_NAME: ${self:service}-${sls:stage}-obtenerUrlImagen
  
functions:
  createProducto:
    handler: create_producto.lambda_handler
    events:
      - http:
          path: producto/create
          method: post
          cors:
            origin: '*' # Permitir cualquier origen
            methods: # Permitir estos métodos HTTP
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
    environment:
      TABLE_NAME: ${self:provider.environment.PRODUCTO_TABLE}

  getProductoById:
    handler: get_producto.lambda_handler
    events:
      - http:
          path: producto/get/{tenant_id}/{producto_id}
          method: get
          cors:
            origin: '*' # Permitir cualquier origen
            methods: # Permitir estos métodos HTTP
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
    environment:
      TABLE_NAME: ${self:provider.environment.PRODUCTO_TABLE}

  deleteProducto:
    handler: delete_producto.lambda_handler
    events:
      - http:
          path: producto/delete
          method: delete
          cors:
            origin: '*' # Permitir cualquier origen
            methods: # Permitir estos métodos HTTP
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
    environment:
      TABLE_NAME: ${self:provider.environment.PRODUCTO_TABLE}


  fetchProductosByTenantId:
  handler: fetch_productos_by_tenant_id.lambda_handler
  events:
    - http:
        path: producto/fetch
        method: get
        cors:
          origin: '*'
          methods:
            - OPTIONS
            - GET
          headers:
            - Content-Type
            - Authorization
            - X-Amz-Date
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
  environment:
    TABLE_NAME: ${self:provider.environment.PRODUCTO_TABLE}


  listProductos:
    handler: list_productos.lambda_handler
    events:
      - http:
          path: producto/list
          method: get
          cors:
            origin: '*' # Permitir cualquier origen
            methods: # Permitir estos métodos HTTP
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
    environment:
      TABLE_NAME: ${self:provider.environment.PRODUCTO_TABLE}
  

  listProductosUrl:
    handler: list_productos_url.lambda_handler
    events:
      - http:
          path: producto/list/url
          method: get
          cors:
            origin: '*' # Permitir cualquier origen
            methods: # Permitir estos métodos HTTP
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
    environment:
      TABLE_NAME: ${self:provider.environment.PRODUCTO_TABLE}

  updateProducto:
    handler: update_producto.lambda_handler
    events:
      - http:
          path: producto/update
          method: patch
          cors:
            origin: '*' # Permitir cualquier origen
            methods: # Permitir estos métodos HTTP
              - OPTIONS
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
    environment:
      TABLE_NAME: ${self:provider.environment.PRODUCTO_TABLE}

  subirImagen:
    handler: subir_imagen_a_s3.lambda_handler

  obtenerUrlImagen:
    handler: obtener_url_imagen.lambda_handler

resources:
  Resources:
    # Bucket S3
    TiendaGrupoNahiaYCompaniaBucketProyecto:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        AccessControl: Private # Acceso privado al bucket
        VersioningConfiguration:
          Status: Enabled  # Habilita el versionado de objetos en el bucket

    # Eliminado el recurso BucketPublicAccessBlock porque no es necesario y está causando errores

    ProductosDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PRODUCTO_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: producto_id
            AttributeType: S
          - AttributeName: stock
            AttributeType: N
          - AttributeName: tenant_id#categoria_nombre
            AttributeType: S
          - AttributeName: precio
            AttributeType: N
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: producto_id
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: LSI_Stock
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: stock
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        GlobalSecondaryIndexes:
          - IndexName: GSI_TenantID_CategoriaNombre
            KeySchema:
              - AttributeName: tenant_id#categoria_nombre
                KeyType: HASH
              - AttributeName: precio
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
